version: '3.5'

services:
  symfony7-api-web:
    container_name: symfony7-api-web
    build:
      context: ./docker/nginx
      args:
        UID: $U_ID
    ports:
      - 250:80
    volumes:
      - ./public:/appdata/www/public
    depends_on:
      - symfony7-api-backend
    networks:
      - symfony-api-platform-network

  symfony7-api-backend:
    container_name: symfony7-api-backend
    build:
      context: docker/php
      args:
        UID: $U_ID
    environment:
      PHP_IDE_CONFIG: serverName=Docker
      XDEBUG_CLIENT_HOST: 172.17.0.1
      XDEBUG_CLIENT_PORT: 9003
    volumes:
      - ./:/appdata/www
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ~/.ssh/id_rsa:/home/appuser/.ssh/id_rsa
    depends_on:
      - symfony7-api-db
    networks:
      - symfony-api-platform-network

  symfony7-api-db:
    container_name: symfony7-api-db
    image: mysql:8
    ports:
      - 36000:3306
    environment:
      MYSQL_DATABASE: symfony_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    command: mysqld --sql_mode="STRICT_ALL_TABLES,NO_ENGINE_SUBSTITUTION"
    volumes:
      - symfony7-api-db-data:/var/lib/mysql
    networks:
      - symfony-api-platform-network

volumes:
  symfony7-api-db-data:


networks:
  symfony-api-platform-network:
    external: true
