parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    ## Users
    App\Modules\Users\Infrastructure\Controllers\UserPostController:
        public: true
        tags: ['controller.service_arguments']

    App\Modules\Users\Infrastructure\Controllers\UserGetController:
        public: true
        tags: [ 'controller.service_arguments' ]

    ## Messages
    App\Modules\Messages\Application\Services\UserCreatedMessageCreator:
        tags: [messenger.message_handler]
